GET http://localhost:5073/games

###
GET http://localhost:5073/games/F631F1F9-E2FA-4E62-9845-ACDAE671AF9B	

###
POST http://localhost:5073/games
Content-Type: application/json

{
	"name": "Test",
	"genreId": "A9C879B8-E948-4BB8-A825-E1A76405FF3A",
	"price": "50.99",
	"releaseDate": "1995-11-18",
	"description": "One of the first games"
}

###
PUT http://localhost:5073/games/F631F1F9-E2FA-4E62-9845-ACDAE671AF9B
Content-Type: application/json

{
	"name": "Left 4 Dead",
	"genreId": "DC336069-A8CA-4305-8CC1-7E7DDE9D2355",
	"price": "99.99",
	"releaseDate": "2008-11-18",
	"description": "One of the best shooters"
}

###
DELETE http://localhost:5073/games/2c415c9a-1d26-46ac-ae0b-344a9ba18e0d
###
GET http://localhost:5073/genres