GET http://localhost:5073/games

###
GET http://localhost:5073/games/F631F1F9-E2FA-4E62-9845-ACDAE671AF9B	

###
POST http://localhost:5073/games
Content-Type: application/json

{
	"name": "Left 4 Dead",
	"genreId": "DC336069-A8CA-4305-8CC1-7E7DDE9D2355",
	"price": "5.99",
	"releaseDate": "2008-11-18",
	"description": "Great shooter"
}

###
PUT http://localhost:5073/games/F631F1F9-E2FA-4E62-9845-ACDAE671AF9B
Content-Type: application/json

{
	"name": "Left 4 Dead",
	"genreId": "DC336069-A8CA-4305-8CC1-7E7DDE9D2355",
	"price": "99.99",
	"releaseDate": "2008-11-18",
	"description": "One of the best shooters"
}

###
DELETE http://localhost:5073/games/a893498d-2c71-40c9-81ce-37e3934499f6

###
GET http://localhost:5073/genres